const String kcountryFlagBaseUrl =
    "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/";
const List<Map<String, String>> kListOfCountry = [
  {'name': 'India', 'code': 'in', 'flag': "${kcountryFlagBaseUrl}IN.svg"},
  {'name': 'USA', 'code': 'us', 'flag': "${kcountryFlagBaseUrl}US.svg"},
  {'name': 'Australia', 'code': 'au', 'flag': "${kcountryFlagBaseUrl}DE.svg"},
  {'name': 'Brazil', 'code': 'br', 'flag': "${kcountryFlagBaseUrl}BR.svg"},
  {'name': 'Canada', 'code': 'ca', 'flag': "${kcountryFlagBaseUrl}CA.svg"},
  {'name': 'China', 'code': 'cn', 'flag': "${kcountryFlagBaseUrl}CN.svg"},
  {'name': 'Egypt', 'code': 'eg', 'flag': "${kcountryFlagBaseUrl}EG.svg"},
  {'name': 'France', 'code': 'fr', 'flag': "${kcountryFlagBaseUrl}FR.svg"},
  {'name': 'Germany', 'code': 'de', 'flag': "${kcountryFlagBaseUrl}DE.svg"},
  {'name': 'Greece', 'code': 'gr', 'flag': "${kcountryFlagBaseUrl}GR.svg"},
  {'name': 'Hong Kong', 'code': 'hk', 'flag': "${kcountryFlagBaseUrl}HK.svg"},
  {'name': 'Israel', 'code': 'il', 'flag': "${kcountryFlagBaseUrl}IL.svg"},
  {'name': 'Italy', 'code': 'it', 'flag': "${kcountryFlagBaseUrl}IT.svg"},
  {'name': 'Japan', 'code': 'jp', 'flag': "${kcountryFlagBaseUrl}JP.svg"},
  {'name': 'Netherlands', 'code': 'nl', 'flag': "${kcountryFlagBaseUrl}NL.svg"},
  {'name': 'Norway', 'code': 'no', 'flag': "${kcountryFlagBaseUrl}NO.svg"},
  {'name': 'Pakistan', 'code': 'pk', 'flag': "${kcountryFlagBaseUrl}DE.svg"},
  {'name': 'peru', 'code': 'pe', 'flag': "${kcountryFlagBaseUrl}PE.svg"},
  {'name': 'Philippins', 'code': 'ph', 'flag': "${kcountryFlagBaseUrl}PH.svg"},
  {'name': 'Portugal', 'code': 'pt', 'flag': "${kcountryFlagBaseUrl}PT.svg"},
  {'name': 'Romania', 'code': 'ro', 'flag': "${kcountryFlagBaseUrl}RO.svg"},
  {
    'name': 'Russian Federation',
    'code': 'ru',
    'flag': "${kcountryFlagBaseUrl}RU.svg"
  },
  {'name': 'Singapore', 'code': 'sg', 'flag': "${kcountryFlagBaseUrl}SG.svg"},
  {'name': 'Spain', 'code': 'es', 'flag': "${kcountryFlagBaseUrl}ES.svg"},
  {'name': 'Sweden', 'code': 'se', 'flag': "${kcountryFlagBaseUrl}SE.svg"},
  {'name': 'Switzerland', 'code': 'ch', 'flag': "${kcountryFlagBaseUrl}CH.svg"},
  {'name': 'Taiwan', 'code': 'tw', 'flag': "${kcountryFlagBaseUrl}TW.svg"},
  {'name': 'Ukraine', 'code': 'ua', 'flag': "${kcountryFlagBaseUrl}UA.svg"},
  {
    'name': 'United Kingdom',
    'code': 'gb',
    'flag': "${kcountryFlagBaseUrl}GB.svg"
  },
];

const List<Map<String, String?>> kListOfTopic = [
  {'name': 'Breaking news', 'code': 'breaking-news'},
  {'name': 'Nation', 'code': 'nation'},
  {'name': 'World', 'code': 'world'},
  {'name': 'Science', 'code': 'science'},
  {'name': 'Technology', 'code': 'technology'},
  {'name': 'Sports', 'code': 'sports'},
  {'name': 'Health', 'code': 'health'},
  {'name': 'Business', 'code': 'business'},
  {'name': 'Entertainment', 'code': 'entertainment'},
];
const List<Map<String, String>> kListOfLanguage = [
  {'name': 'Arabic', 'code': 'ar'},
  {'name': 'Chinese', 'code': 'zh'},
  {'name': 'Duch', 'code': 'nl'},
  {'name': 'English', 'code': 'en'},
  {'name': 'French', 'code': 'fr'},
  {'name': 'German', 'code': 'de'},
  {'name': 'Greek', 'code': 'el'},
  {'name': 'Hebrew', 'code': 'he'},
  {'name': 'Hindi', 'code': 'hi'},
  {'name': 'Italian', 'code': 'it'},
  {'name': 'Japanese', 'code': 'ja'},
  {'name': 'Malayalam', 'code': 'ml'},
  {'name': 'Marathi', 'code': 'mr'},
  {'name': 'Norwegian', 'code': 'no'},
  {'name': 'Portuguese', 'code': 'pt'},
  {'name': 'Romanian', 'code': 'ro'},
  {'name': 'Russian', 'code': 'ru'},
  {'name': 'Spanish', 'code': 'es'},
  {'name': 'Swedish', 'code': 'sv'},
  {'name': 'Tamil', 'code': 'ta'},
  {'name': 'Telgu', 'code': 'te'},
  {'name': 'Ukrainian', 'code': 'uk'},
];
